### ISSUE TITLE
Few of the courses are not parsed while trying to download

### ISSUE THREAD

**Issue by suraj-2306** [abhijeetviswa/CMS-Scraper#3]
Few of the courses are not Downloaded when the request is made to scrape registered courses.
command invoked,
`./cmsscraper.py  token YYY  --session-cookie XXX`

Courses like 
ECON F211 PRINCIPLES OF ECONOMICS L
are scraped successfully,

Some course names that are not downloaded or processed are of the format 
CS/ECE/EEE/INSTR F241 MICROPROC & INTERFACING L
ECE/EEE/INSTR F244 MICROELECTRONIC CIRCUITS L

The suspected issue: 
the regex isn't exactly matching the course name and returning no course name to variable match in line 190, in enquee_all_downloads() function.

Python interpreter used: Python 3.8.5.
OS: Ubuntu 20.04

**Comment by abhijeetviswa** [comment]
This time, they switched from using backslashes to forward slashes. I noticed that this was broken working on 2a68e8c7f2ad056871980e78bca273f1ed54ab7c and modified the regex in that commit itself. Pull the latest changes and test it out. If the issue has been fixed, close this thread.

**Comment by suraj-2306** [comment]
Yes, the issue has been resolved.
